// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBase.proto

#ifndef PROTOBUF_MessageBase_2eproto__INCLUDED
#define PROTOBUF_MessageBase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageBase_2eproto();
void protobuf_AssignDesc_MessageBase_2eproto();
void protobuf_ShutdownFile_MessageBase_2eproto();

class MessageBase;

enum MessageBase_Opcode {
  MessageBase_Opcode_UNKNOWN = 0,
  MessageBase_Opcode_REGISTER = 1,
  MessageBase_Opcode_LOGIN = 2,
  MessageBase_Opcode_LOGOUT = 3
};
bool MessageBase_Opcode_IsValid(int value);
const MessageBase_Opcode MessageBase_Opcode_Opcode_MIN = MessageBase_Opcode_UNKNOWN;
const MessageBase_Opcode MessageBase_Opcode_Opcode_MAX = MessageBase_Opcode_LOGOUT;
const int MessageBase_Opcode_Opcode_ARRAYSIZE = MessageBase_Opcode_Opcode_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageBase_Opcode_descriptor();
inline const ::std::string& MessageBase_Opcode_Name(MessageBase_Opcode value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageBase_Opcode_descriptor(), value);
}
inline bool MessageBase_Opcode_Parse(
    const ::std::string& name, MessageBase_Opcode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageBase_Opcode>(
    MessageBase_Opcode_descriptor(), name, value);
}
// ===================================================================

class MessageBase : public ::google::protobuf::Message {
 public:
  MessageBase();
  virtual ~MessageBase();

  MessageBase(const MessageBase& from);

  inline MessageBase& operator=(const MessageBase& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageBase& default_instance();

  void Swap(MessageBase* other);

  // implements Message ----------------------------------------------

  MessageBase* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageBase& from);
  void MergeFrom(const MessageBase& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MessageBase_Opcode Opcode;
  static const Opcode UNKNOWN = MessageBase_Opcode_UNKNOWN;
  static const Opcode REGISTER = MessageBase_Opcode_REGISTER;
  static const Opcode LOGIN = MessageBase_Opcode_LOGIN;
  static const Opcode LOGOUT = MessageBase_Opcode_LOGOUT;
  static inline bool Opcode_IsValid(int value) {
    return MessageBase_Opcode_IsValid(value);
  }
  static const Opcode Opcode_MIN =
    MessageBase_Opcode_Opcode_MIN;
  static const Opcode Opcode_MAX =
    MessageBase_Opcode_Opcode_MAX;
  static const int Opcode_ARRAYSIZE =
    MessageBase_Opcode_Opcode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Opcode_descriptor() {
    return MessageBase_Opcode_descriptor();
  }
  static inline const ::std::string& Opcode_Name(Opcode value) {
    return MessageBase_Opcode_Name(value);
  }
  static inline bool Opcode_Parse(const ::std::string& name,
      Opcode* value) {
    return MessageBase_Opcode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 majorVersion = 1;
  inline bool has_majorversion() const;
  inline void clear_majorversion();
  static const int kMajorVersionFieldNumber = 1;
  inline ::google::protobuf::int32 majorversion() const;
  inline void set_majorversion(::google::protobuf::int32 value);

  // required int32 minurVersion = 2;
  inline bool has_minurversion() const;
  inline void clear_minurversion();
  static const int kMinurVersionFieldNumber = 2;
  inline ::google::protobuf::int32 minurversion() const;
  inline void set_minurversion(::google::protobuf::int32 value);

  // required int32 buildVersion = 3;
  inline bool has_buildversion() const;
  inline void clear_buildversion();
  static const int kBuildVersionFieldNumber = 3;
  inline ::google::protobuf::int32 buildversion() const;
  inline void set_buildversion(::google::protobuf::int32 value);

  // required .MessageBase.Opcode code = 4 [default = UNKNOWN];
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 4;
  inline ::MessageBase_Opcode code() const;
  inline void set_code(::MessageBase_Opcode value);

  // @@protoc_insertion_point(class_scope:MessageBase)
 private:
  inline void set_has_majorversion();
  inline void clear_has_majorversion();
  inline void set_has_minurversion();
  inline void clear_has_minurversion();
  inline void set_has_buildversion();
  inline void clear_has_buildversion();
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 majorversion_;
  ::google::protobuf::int32 minurversion_;
  ::google::protobuf::int32 buildversion_;
  int code_;
  friend void  protobuf_AddDesc_MessageBase_2eproto();
  friend void protobuf_AssignDesc_MessageBase_2eproto();
  friend void protobuf_ShutdownFile_MessageBase_2eproto();

  void InitAsDefaultInstance();
  static MessageBase* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageBase

// required int32 majorVersion = 1;
inline bool MessageBase::has_majorversion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageBase::set_has_majorversion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageBase::clear_has_majorversion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageBase::clear_majorversion() {
  majorversion_ = 0;
  clear_has_majorversion();
}
inline ::google::protobuf::int32 MessageBase::majorversion() const {
  // @@protoc_insertion_point(field_get:MessageBase.majorVersion)
  return majorversion_;
}
inline void MessageBase::set_majorversion(::google::protobuf::int32 value) {
  set_has_majorversion();
  majorversion_ = value;
  // @@protoc_insertion_point(field_set:MessageBase.majorVersion)
}

// required int32 minurVersion = 2;
inline bool MessageBase::has_minurversion() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageBase::set_has_minurversion() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageBase::clear_has_minurversion() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageBase::clear_minurversion() {
  minurversion_ = 0;
  clear_has_minurversion();
}
inline ::google::protobuf::int32 MessageBase::minurversion() const {
  // @@protoc_insertion_point(field_get:MessageBase.minurVersion)
  return minurversion_;
}
inline void MessageBase::set_minurversion(::google::protobuf::int32 value) {
  set_has_minurversion();
  minurversion_ = value;
  // @@protoc_insertion_point(field_set:MessageBase.minurVersion)
}

// required int32 buildVersion = 3;
inline bool MessageBase::has_buildversion() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageBase::set_has_buildversion() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageBase::clear_has_buildversion() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageBase::clear_buildversion() {
  buildversion_ = 0;
  clear_has_buildversion();
}
inline ::google::protobuf::int32 MessageBase::buildversion() const {
  // @@protoc_insertion_point(field_get:MessageBase.buildVersion)
  return buildversion_;
}
inline void MessageBase::set_buildversion(::google::protobuf::int32 value) {
  set_has_buildversion();
  buildversion_ = value;
  // @@protoc_insertion_point(field_set:MessageBase.buildVersion)
}

// required .MessageBase.Opcode code = 4 [default = UNKNOWN];
inline bool MessageBase::has_code() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageBase::set_has_code() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageBase::clear_has_code() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageBase::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::MessageBase_Opcode MessageBase::code() const {
  // @@protoc_insertion_point(field_get:MessageBase.code)
  return static_cast< ::MessageBase_Opcode >(code_);
}
inline void MessageBase::set_code(::MessageBase_Opcode value) {
  assert(::MessageBase_Opcode_IsValid(value));
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MessageBase.code)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageBase_Opcode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageBase_Opcode>() {
  return ::MessageBase_Opcode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageBase_2eproto__INCLUDED
