// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBase.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageBase.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageBase_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageBase_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageBase_Opcode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageBase_2eproto() {
  protobuf_AddDesc_MessageBase_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageBase.proto");
  GOOGLE_CHECK(file != NULL);
  MessageBase_descriptor_ = file->message_type(0);
  static const int MessageBase_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, majorversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, minurversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, buildversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, code_),
  };
  MessageBase_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageBase_descriptor_,
      MessageBase::default_instance_,
      MessageBase_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageBase, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageBase));
  MessageBase_Opcode_descriptor_ = MessageBase_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageBase_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageBase_descriptor_, &MessageBase::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageBase_2eproto() {
  delete MessageBase::default_instance_;
  delete MessageBase_reflection_;
}

void protobuf_AddDesc_MessageBase_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021MessageBase.proto\"\267\001\n\013MessageBase\022\024\n\014m"
    "ajorVersion\030\001 \002(\005\022\024\n\014minurVersion\030\002 \002(\005\022"
    "\024\n\014buildVersion\030\003 \002(\005\022*\n\004code\030\004 \002(\0162\023.Me"
    "ssageBase.Opcode:\007UNKNOWN\":\n\006Opcode\022\013\n\007U"
    "NKNOWN\020\000\022\014\n\010REGISTER\020\001\022\t\n\005LOGIN\020\002\022\n\n\006LOG"
    "OUT\020\003B,\n\025com.meteor.minaserverB\023MessageB"
    "aseProtoBuf", 251);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageBase.proto", &protobuf_RegisterTypes);
  MessageBase::default_instance_ = new MessageBase();
  MessageBase::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageBase_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageBase_2eproto {
  StaticDescriptorInitializer_MessageBase_2eproto() {
    protobuf_AddDesc_MessageBase_2eproto();
  }
} static_descriptor_initializer_MessageBase_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* MessageBase_Opcode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageBase_Opcode_descriptor_;
}
bool MessageBase_Opcode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const MessageBase_Opcode MessageBase::UNKNOWN;
const MessageBase_Opcode MessageBase::REGISTER;
const MessageBase_Opcode MessageBase::LOGIN;
const MessageBase_Opcode MessageBase::LOGOUT;
const MessageBase_Opcode MessageBase::Opcode_MIN;
const MessageBase_Opcode MessageBase::Opcode_MAX;
const int MessageBase::Opcode_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int MessageBase::kMajorVersionFieldNumber;
const int MessageBase::kMinurVersionFieldNumber;
const int MessageBase::kBuildVersionFieldNumber;
const int MessageBase::kCodeFieldNumber;
#endif  // !_MSC_VER

MessageBase::MessageBase()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageBase)
}

void MessageBase::InitAsDefaultInstance() {
}

MessageBase::MessageBase(const MessageBase& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageBase)
}

void MessageBase::SharedCtor() {
  _cached_size_ = 0;
  majorversion_ = 0;
  minurversion_ = 0;
  buildversion_ = 0;
  code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageBase::~MessageBase() {
  // @@protoc_insertion_point(destructor:MessageBase)
  SharedDtor();
}

void MessageBase::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MessageBase::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageBase::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageBase_descriptor_;
}

const MessageBase& MessageBase::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageBase_2eproto();
  return *default_instance_;
}

MessageBase* MessageBase::default_instance_ = NULL;

MessageBase* MessageBase::New() const {
  return new MessageBase;
}

void MessageBase::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessageBase*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(majorversion_, code_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageBase::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageBase)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 majorVersion = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &majorversion_)));
          set_has_majorversion();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_minurVersion;
        break;
      }

      // required int32 minurVersion = 2;
      case 2: {
        if (tag == 16) {
         parse_minurVersion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &minurversion_)));
          set_has_minurversion();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_buildVersion;
        break;
      }

      // required int32 buildVersion = 3;
      case 3: {
        if (tag == 24) {
         parse_buildVersion:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &buildversion_)));
          set_has_buildversion();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_code;
        break;
      }

      // required .MessageBase.Opcode code = 4 [default = UNKNOWN];
      case 4: {
        if (tag == 32) {
         parse_code:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MessageBase_Opcode_IsValid(value)) {
            set_code(static_cast< ::MessageBase_Opcode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(4, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageBase)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageBase)
  return false;
#undef DO_
}

void MessageBase::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageBase)
  // required int32 majorVersion = 1;
  if (has_majorversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->majorversion(), output);
  }

  // required int32 minurVersion = 2;
  if (has_minurversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->minurversion(), output);
  }

  // required int32 buildVersion = 3;
  if (has_buildversion()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->buildversion(), output);
  }

  // required .MessageBase.Opcode code = 4 [default = UNKNOWN];
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->code(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageBase)
}

::google::protobuf::uint8* MessageBase::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageBase)
  // required int32 majorVersion = 1;
  if (has_majorversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->majorversion(), target);
  }

  // required int32 minurVersion = 2;
  if (has_minurversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->minurversion(), target);
  }

  // required int32 buildVersion = 3;
  if (has_buildversion()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->buildversion(), target);
  }

  // required .MessageBase.Opcode code = 4 [default = UNKNOWN];
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->code(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageBase)
  return target;
}

int MessageBase::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 majorVersion = 1;
    if (has_majorversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->majorversion());
    }

    // required int32 minurVersion = 2;
    if (has_minurversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->minurversion());
    }

    // required int32 buildVersion = 3;
    if (has_buildversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->buildversion());
    }

    // required .MessageBase.Opcode code = 4 [default = UNKNOWN];
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->code());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageBase::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageBase* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageBase*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageBase::MergeFrom(const MessageBase& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_majorversion()) {
      set_majorversion(from.majorversion());
    }
    if (from.has_minurversion()) {
      set_minurversion(from.minurversion());
    }
    if (from.has_buildversion()) {
      set_buildversion(from.buildversion());
    }
    if (from.has_code()) {
      set_code(from.code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageBase::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageBase::CopyFrom(const MessageBase& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageBase::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void MessageBase::Swap(MessageBase* other) {
  if (other != this) {
    std::swap(majorversion_, other->majorversion_);
    std::swap(minurversion_, other->minurversion_);
    std::swap(buildversion_, other->buildversion_);
    std::swap(code_, other->code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageBase::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageBase_descriptor_;
  metadata.reflection = MessageBase_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
